<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>realsense_gz_plugin</name>
  <version>0.1.0</version>
  <description>
    Custom Gazebo Harmonic RealSense sensor package for gz-sim8 and
    gz-sensors8. Provides custom camera, depth camera, and RGBD sensors
    with optional pointcloud publication and ROS-friendly frame handling.
  </description>

  <maintainer email="toridebraus@gmail.com">Davide Torielli</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gz-plugin-vendor</depend>
  <depend>gz-sensors-vendor</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
